# Generated manually to match the current `Pais` model with `nombre` field
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('capital', models.CharField(max_length=100)),
                ('poblacion', models.BigIntegerField()),
                ('area', models.FloatField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'paises',
                'ordering': ['nombre'],
            },
        ),
    ]
# Generated by Django 4.2.26 on 2025-11-24 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pais', models.CharField(max_length=100)),
                ('capital', models.CharField(max_length=100)),
                ('poblacion', models.BigIntegerField()),
                ('area', models.FloatField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'paises',
                'ordering': ['pais'],
            },
        ),
    ]
